// ============================================
// Minakshi Makeup & Hair — Site Data
// 70% English / 30% Hinglish for warmth & desi touch
// ============================================

export const siteConfig = {
  name: "Minakshi Makeup & Hair",
  owner: "Minakshi",
  tagline: "Where Beauty Meets Artistry",
  description: "Mumbai's trusted Bridal Makeup Artist with 8+ years of experience and 500+ happy brides. Every culture, every style — aapki khoobsurti, our promise.",
  phone: "+919172235347",
  email: "minakshimakeupandhair@gmail.com",
  instagram: "https://www.instagram.com/minakshimakeupandhair",
  youtube: "https://youtube.com/@minakshimakeupandhair",
  whatsappLink: "https://wa.me/919172235347?text=Hi%20Minakshi%2C%20I%27d%20love%20to%20know%20more%20about%20your%20bridal%20makeup%20services.%20Please%20share%20the%20details!",
  googleReviewsLink: "https://g.co/kgs/abc123",
  location: "Mumbai",
  availability: "Available Globally",
  experience: 8,
  bridesCount: 500,
  rating: 4.9,
  reviewCount: 171,
  bookingStatus: "Now Booking",
};

export const stats = [
  { number: 8, suffix: "+", label: "Years of Experience" },
  { number: 500, suffix: "+", label: "Happy Brides" },
  { number: 4.9, suffix: "", label: "Google Rating" },
  { number: 50, suffix: "+", label: "Destination Weddings" },
];

export const services = [
  {
    id: "bridal",
    title: "Bridal Makeup & Hair HD / Natural",
    description: "Your special day deserves a flawless look — choose HD for camera-perfect finish or Natural for a soft, radiant glow. Every culture, every style.",
    tags: ["HD Finish", "Natural Look", "Trial Session"],
    image: "/images/services/bridal-service.jpg",
    popular: true,
  },
  {
    id: "pre-post-wedding",
    title: "Pre / Post Wedding Functions",
    description: "From Haldi & Mehendi to Reception — stunning looks for every function before and after the big day.",
    tags: ["Engagement", "Haldi", "Reception"],
    image: "/images/services/engagement-service.jpg",
    popular: true,
  },
  {
    id: "party",
    title: "Party Makeup & Hair",
    description: "Glamorous looks for every occasion — cocktail nights, festive celebrations, and special evenings out.",
    tags: ["Evening Glam", "Long-lasting", "Photo-ready"],
    image: "/images/services/reception-service.jpg",
  },
  {
    id: "baby-shower-birthday",
    title: "Baby Shower / Birthday Makeup & Hair",
    description: "Soft, glowing makeup for your special celebration. Gentle products with a radiant, picture-perfect finish.",
    tags: ["Soft Glam", "Gentle Products", "Natural Glow"],
    image: "/images/services/baby-shower-service.jpg",
  },
  {
    id: "classes",
    title: "Makeup Classes / Workshops",
    description: "Learn professional makeup techniques from an expert. Perfect for beginners and aspiring artists — hands-on training with premium products.",
    tags: ["Hands-on Training", "Beginner Friendly", "Certificate"],
    image: "/images/services/hair-service.jpg",
  },
  {
    id: "destination",
    title: "Destination Bridal Makeup",
    description: "Dream destination wedding? We travel with you! Full bridal makeup & hair services wherever your celebration takes you.",
    tags: ["Travel Ready", "Full Coverage", "Destination"],
    image: "/images/services/cinematic-service.jpg",
  },
];

export const portfolio = [
  {
    id: 1,
    title: "Marathi Bride",
    category: "bridal",
    image: "/images/portfolio/marathi-bride.jpg",
    description: "No filter ahead — pure elegance and charm",
  },
  {
    id: 2,
    title: "Engagement Glamour",
    category: "engagement",
    image: "/images/portfolio/engagement-glamour.jpg",
    description: "Soft glam finish that everyone loved",
  },
  {
    id: 3,
    title: "Natural Beauty Look",
    category: "engagement",
    image: "/images/portfolio/engagement-natural.jpg",
    description: "No lashes, no lenses — just pure natural beauty",
  },
  {
    id: 4,
    title: "Soft Pink Bride",
    category: "bridal",
    image: "/images/portfolio/soft-pink-bride.jpg",
    description: "Soft pink, soft lips — a dreamy bridal look",
  },
  {
    id: 5,
    title: "Engagement Makeover",
    category: "engagement",
    image: "/images/portfolio/engagement-makeover.jpg",
    description: "Make your big day truly special",
  },
  {
    id: 6,
    title: "South Indian Bride",
    category: "bridal",
    image: "/images/portfolio/south-indian.jpg",
    description: "Traditional South Indian bridal elegance at its best",
  },
  {
    id: 7,
    title: "Reception Glam",
    category: "party",
    image: "/images/portfolio/reception-glam.jpg",
    description: "Glamorous reception look for the evening celebration",
  },
  {
    id: 8,
    title: "Cinematic Wedding",
    category: "bridal",
    image: "/images/portfolio/cinematic-wedding.jpg",
    description: "Jayesh & Pooja — a cinematic beginning to forever",
  },
  {
    id: 9,
    title: "Flower Art Hair",
    category: "pre-wedding",
    image: "/images/portfolio/flower-art.jpg",
    description: "Intricate flower art with full glamour styling",
  },
  {
    id: 10,
    title: "Bengali HD Look",
    category: "bridal",
    image: "/images/portfolio/bengali-hd.jpg",
    description: "Gorgeous Bengali bridal look with HD finish — before & after",
  },
  {
    id: 11,
    title: "Wedding Look",
    category: "bridal",
    image: "/images/portfolio/wedding-look.jpg",
    description: "Soft glam, true love, perfect moment",
  },
  {
    id: 12,
    title: "Engagement Soft Glam",
    category: "engagement",
    image: "/images/portfolio/engagement-soft.jpg",
    description: "Beautiful engagement makeover with soft glam finish",
  },
  {
    id: 13,
    title: "Minimal Wedding Look",
    category: "bridal",
    image: "/images/portfolio/minimal-wedding.jpg",
    description: "Less is more — minimal yet stunning bridal look",
  },
  {
    id: 14,
    title: "Glamorous Engagement",
    category: "engagement",
    image: "/images/portfolio/glamorous-engagement.jpg",
    description: "Full glamour engagement — sab dekhte reh gaye!",
  },
  {
    id: 15,
    title: "Engagement Bride",
    category: "engagement",
    image: "/images/portfolio/engagement-bride-1.jpg",
    description: "Elegant engagement bride with perfect finishing",
  },
  {
    id: 16,
    title: "Glamorous Look",
    category: "engagement",
    image: "/images/portfolio/glamorous-engagement-2.jpg",
    description: "Another gorgeous engagement transformation",
  },
  {
    id: 17,
    title: "Reception Makeover",
    category: "party",
    image: "/images/portfolio/reception-makeover.jpg",
    description: "Reception glamour at its finest",
  },
  {
    id: 18,
    title: "Engagement Beauty",
    category: "engagement",
    image: "/images/portfolio/engagement-bride-2.jpg",
    description: "A beautiful engagement look — natural and graceful",
  },
  {
    id: 19,
    title: "Reception Evening Look",
    category: "party",
    image: "/images/portfolio/reception-look.jpg",
    description: "Perfect glamorous look for evening receptions",
  },
  {
    id: 20,
    title: "Minimal Bride",
    category: "bridal",
    image: "/images/portfolio/minimal-wedding-2.jpg",
    description: "Less is more — another stunning minimal look",
  },
  {
    id: 21,
    title: "Glowing Wedding Look",
    category: "bridal",
    image: "/images/portfolio/glowing-wedding.jpg",
    description: "A bride glowing with love and happiness",
  },
  {
    id: 22,
    title: "HD Siders Look",
    category: "before-after",
    image: "/images/portfolio/hd-siders-look.jpg",
    description: "Professional siders look with HD finish — before & after",
  },
  {
    id: 23,
    title: "Classic Wedding",
    category: "bridal",
    image: "/images/portfolio/wedding-classic.jpg",
    description: "Timeless classic wedding look",
  },
  {
    id: 24,
    title: "Radiant Bride",
    category: "bridal",
    image: "/images/portfolio/glowing-wedding-2.jpg",
    description: "Glow from within — radiant bridal beauty",
  },
  {
    id: 25,
    title: "Reception Queen",
    category: "party",
    image: "/images/portfolio/reception-makeover-2.jpg",
    description: "The reception queen — all eyes on her",
  },
  {
    id: 26,
    title: "Happy Bride",
    category: "bridal",
    image: "/images/portfolio/glowing-wedding-3.jpg",
    description: "Glowing with happiness — a beautiful bride",
  },
  {
    id: 100,
    title: 'Real Bride Glow',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-001.jpg',
    description: 'Engagement makeover',
  },
  {
    id: 101,
    title: 'Bridal Beauty',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-002.jpg',
    description: 'Engagement makeover',
  },
  {
    id: 102,
    title: 'Wedding Day Magic',
    category: 'before-after',
    image: '/images/portfolio/insta/insta-003.jpg',
    description: 'HD siders look — before & after transformation',
  },
  {
    id: 103,
    title: 'Glam Goals',
    category: 'pre-wedding',
    image: '/images/portfolio/insta/insta-004.jpg',
    description: 'Pre-wedding glam look',
  },
  {
    id: 104,
    title: 'Stunning Look',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-005.jpg',
    description: 'Engagement makeover',
  },
  {
    id: 105,
    title: 'Dreamy Dulhan',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-006.jpg',
    description: 'No filter ahead — pure real beauty',
  },
  {
    id: 106,
    title: 'Picture Perfect',
    category: 'before-after',
    image: '/images/portfolio/insta/insta-007.jpg',
    description: 'HD siders look — stunning transformation',
  },
  {
    id: 107,
    title: 'Pure Elegance',
    category: 'pre-wedding',
    image: '/images/portfolio/insta/insta-008.jpg',
    description: 'Pre-wedding elegance',
  },
  {
    id: 108,
    title: 'Sundar Lagi',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-009.jpg',
    description: 'No filter ahead — pure real beauty',
  },
  {
    id: 109,
    title: 'Wedding Vibes',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-010.jpg',
    description: 'Wedding look',
  },
  {
    id: 110,
    title: 'Bridal Diary',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-011.jpg',
    description: 'Engagement bride',
  },
  {
    id: 111,
    title: 'Soft Glam Story',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-012.jpg',
    description: 'Beautiful glamorous engagement bride',
  },
  {
    id: 112,
    title: 'Gorgeous Bride',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-013.jpg',
    description: 'Minimal wedding look',
  },
  {
    id: 113,
    title: 'Pyaari Dulhan',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-014.jpg',
    description: 'No filter ahead — pure real beauty',
  },
  {
    id: 114,
    title: 'Mehendi Glow',
    category: 'haldi',
    image: '/images/portfolio/insta/insta-015.jpg',
    description: 'Haldi & Mehendi glow — radiant and festive',
  },
  {
    id: 115,
    title: 'Forever Look',
    category: 'party',
    image: '/images/portfolio/insta/insta-016.jpg',
    description: 'Party makeover',
  },
  {
    id: 116,
    title: 'Royal Bride',
    category: 'party',
    image: '/images/portfolio/insta/insta-017.jpg',
    description: 'Party makeover',
  },
  {
    id: 117,
    title: 'Modern Glamour',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-018.jpg',
    description: 'Engagement bride',
  },
  {
    id: 118,
    title: 'Timeless Beauty',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-019.jpg',
    description: 'Minimal wedding look',
  },
  {
    id: 119,
    title: 'Wedding Wonder',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-020.jpg',
    description: 'Beautiful glamorous engagement bride',
  },
  {
    id: 120,
    title: 'Bridal Charm',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-021.jpg',
    description: 'Engagement bride',
  },
  {
    id: 121,
    title: 'Real Magic',
    category: 'haldi',
    image: '/images/portfolio/insta/insta-022.jpg',
    description: 'Haldi ceremony glow',
  },
  {
    id: 122,
    title: 'Sparkle & Shine',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-023.jpg',
    description: 'Glowing with love and happiness',
  },
  {
    id: 123,
    title: 'Pretty in Glam',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-024.jpg',
    description: 'Glowing with love and happiness',
  },
  {
    id: 124,
    title: 'Bride Vibes',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-025.jpg',
    description: 'Glowing with love and happiness',
  },
  {
    id: 125,
    title: 'Cinema Bride',
    category: 'before-after',
    image: '/images/portfolio/insta/insta-026.jpg',
    description: 'Before & after — minimal wedding transformation',
  },
  {
    id: 126,
    title: 'Dream Day Look',
    category: 'haldi',
    image: '/images/portfolio/insta/insta-027.jpg',
    description: 'Haldi ceremony look — festive and vibrant',
  },
];

// Real Google Reviews — scraped from Google Maps (4.9 rating, 171+ reviews)
export const reviews = [
  {
    name: "Shubhangi Gawas",
    text: "Absolutely in love with my bridal makeup! She understood my requirements perfectly and delivered exactly what I had envisioned. The makeup was flawless, elegant, and long-lasting. I felt confident, radiant, and truly like the best version of myself on my big day.",
    rating: 5,
    event: "Bridal Makeup",
    image: "/images/reviews/review-1.jpg",
  },
  {
    name: "Khushboo Chaurasia",
    text: "I couldn't have asked for a better makeup artist for my special day. She understood exactly what I wanted and enhanced my features so beautifully while keeping the look elegant and natural. The makeup stayed flawless throughout the entire event, despite all the rituals, photos, and emotions.",
    rating: 5,
    event: "Bridal Makeup",
    image: "/images/reviews/review-2.jpg",
  },
  {
    name: "Rupa Borkar",
    text: "Had the most amazing experience with Minakshi for my event! She's so talented, patient, and made me feel incredibly comfortable. The makeup was natural yet glam, photographed beautifully, and stayed put all day. She truly brought my vision to life!",
    rating: 5,
    event: "Engagement Makeup",
    image: "/images/reviews/review-3.jpg",
  },
  {
    name: "Aparna Panigrahy",
    text: "Absolutely loved her work! She created the exact engagement look I had envisioned — and honestly, even better than I imagined. Her attention to detail is amazing. On top of that, she is so kind, polite, and makes you feel completely comfortable. Highly recommend!",
    rating: 5,
    event: "Engagement Makeup",
    image: "/images/reviews/review-4.jpg",
  },
  {
    name: "Poornima Nalavade",
    text: "Thank you so much for the amazing makeup! I loved how you kept it so natural yet radiant. It lasted all day/night, and my first/second look turned out beautifully. I received so many compliments. You are truly very talented!",
    rating: 5,
    event: "Party Makeup",
    image: "/images/reviews/review-5.jpg",
  },
  {
    name: "Purnima Singh",
    text: "Just wanted to say a huge thank you for the amazing look you gave me — you totally nailed it! Felt so beautiful and confident, and everyone kept complimenting my look. Really appreciate your talent, professionalism, and the extra effort of making me calm.",
    rating: 4,
    event: "Bridal Makeup",
    image: "/images/reviews/review-1.jpg",
  },
  {
    name: "Namrata Purabia",
    text: "I found you on the map, and you turned out to be the best find ever. Thank you for making me look so beautiful on my special day. Who knew a map search would lead me to such an amazing makeup artist? Thank you for the perfect look Minakshi Di!",
    rating: 5,
    event: "Bridal Makeup",
    image: "/images/reviews/review-2.jpg",
  },
  {
    name: "Simantini Deochake",
    text: "Minakshi is a fabulous makeup artist. She is patient and innovative in giving you the perfect look. She transformed me with her magic at my son's Thread ceremony function. Thank you Minakshi!",
    rating: 5,
    event: "Party Makeup",
    image: "/images/reviews/review-3.jpg",
  },
];

export const vendorPartners = [
  {
    name: "Shutter Snap Photography",
    role: "Wedding Photography",
    instagram: "@shutter_snap_photography_20",
  },
  {
    name: "Shutter Soul Studio",
    role: "Cinematography",
    instagram: "@shuttersoul__studio",
  },
  {
    name: "Vid Tam Photography",
    role: "Video Editing",
    instagram: "@vid.tam_pho2graphy",
  },
];

export const processSteps = [
  {
    step: 1,
    title: "Inquiry",
    description: "Reach out via WhatsApp or our contact form. Tell us about your event, date, and the look you envision.",
    icon: "message",
  },
  {
    step: 2,
    title: "Consultation",
    description: "We discuss your outfit, jewellery, venue, and preferences in detail. Together we create your perfect look concept.",
    icon: "sparkle",
  },
  {
    step: 3,
    title: "Trial Session",
    description: "A pre-wedding trial to finalize your look. We fine-tune every detail until you are absolutely in love with it.",
    icon: "palette",
  },
  {
    step: 4,
    title: "Aapka Big Day",
    description: "On the day, we arrive early, set up, and create magic. You relax — we'll make you look your most beautiful self.",
    icon: "crown",
  },
];

export const marqueeItems = [
  "Bridal Makeup & Hair",
  "Pre-Wedding Functions",
  "Party Makeup",
  "Baby Shower Glam",
  "Birthday Makeup",
  "Makeup Classes",

  "Destination Bridal",
  "HD Makeup",
  "Natural Makeup",
  "Hair Styling",
  "Post-Wedding Looks",
];

export const portfolioCategories = [
  { id: "all", label: "All" },
  { id: "bridal", label: "Bridal Makeup Looks" },
  { id: "party", label: "Party Looks" },
  { id: "engagement", label: "Engagement Looks" },
  { id: "pre-wedding", label: "Pre-Wedding Looks" },
  { id: "before-after", label: "Before-After Looks" },
  { id: "haldi", label: "Haldi Looks" },
];
