// ============================================
// Minakshi Makeup & Hair — Site Data
// 70% English / 30% Hinglish for warmth & desi touch
// ============================================

export const siteConfig = {
  name: "Minakshi Makeup & Hair",
  owner: "Minakshi",
  tagline: "Where Beauty Meets Artistry",
  description: "Mumbai's trusted Bridal Makeup Artist with 8+ years of experience and 500+ happy brides. Every culture, every style — aapki khoobsurti, our promise.",
  phone: "+919172235347",
  email: "minakshimakeupandhair@gmail.com",
  instagram: "https://www.instagram.com/minakshimakeupandhair",
  youtube: "https://youtube.com/@minakshimakeupandhair",
  whatsappLink: "https://wa.me/919172235347?text=Hi%20Minakshi%2C%20I%27d%20love%20to%20know%20more%20about%20your%20bridal%20makeup%20services.%20Please%20share%20the%20details!",
  googleReviewsLink: "https://g.co/kgs/abc123",
  location: "Mumbai (Vasai-Virar)",
  availability: "Available Globally",
  experience: 8,
  bridesCount: 500,
  rating: 4.9,
  reviewCount: 168,
  bookingStatus: "Now Booking",
};

export const stats = [
  { number: 8, suffix: "+", label: "Years of Experience" },
  { number: 500, suffix: "+", label: "Happy Brides" },
  { number: 4.9, suffix: "", label: "Google Rating" },
  { number: 50, suffix: "+", label: "Destination Weddings" },
];

export const services = [
  {
    id: "bridal",
    title: "Bridal Makeup",
    description: "Your special day deserves a flawless look — from traditional Marathi to modern glam, every culture, every style, with artistry that lasts.",
    tags: ["HD Finish", "Trial Session", "Touch-up Kit"],
    image: "/images/services/bridal-service.jpg",
    popular: true,
  },
  {
    id: "engagement",
    title: "Engagement Makeup",
    description: "Our most popular service! A radiant glow for your engagement — with or without lashes, the choice is yours.",
    tags: ["No-Lash Option", "Soft Glam", "HD Ready"],
    image: "/images/services/engagement-service.jpg",
    popular: true,
  },
  {
    id: "reception",
    title: "Reception Makeup",
    description: "Glamorous evening looks that photograph beautifully and last all night long. Camera-ready finish guaranteed.",
    tags: ["Evening Glam", "Long-lasting", "Photo-ready"],
    image: "/images/services/reception-service.jpg",
  },
  {
    id: "south-indian",
    title: "South Indian Bridal",
    description: "Traditional South Indian bridal looks with authentic jewellery styling and expert saree draping.",
    tags: ["Jewellery Styling", "Traditional", "Saree Draping"],
    image: "/images/services/south-indian-service.jpg",
  },
  {
    id: "bengali",
    title: "Bengali Bridal",
    description: "Beautiful Bengali bridal looks with HD finish and authentic styling that honours cultural traditions.",
    tags: ["HD Makeup", "Cultural Styling", "Authentic"],
    image: "/images/services/bengali-service.jpg",
  },
  {
    id: "baby-shower",
    title: "Baby Shower Makeup",
    description: "Soft, glowing makeup for your special celebration. Gentle products with a radiant, natural finish.",
    tags: ["Soft Glam", "Gentle Products", "Natural Glow"],
    image: "/images/services/baby-shower-service.jpg",
  },
  {
    id: "hair",
    title: "Hair Styling",
    description: "Elegant updos, flowing curls, flower art, and accessory placement — complete hair styling bundled with every makeup service.",
    tags: ["Bridal Hair", "Updos", "Flower Art"],
    image: "/images/services/hair-service.jpg",
  },
  {
    id: "cinematic",
    title: "Cinematic Wedding Package",
    description: "The complete team — makeup, photography, cinematography, and editing. One booking, full coverage, cinematic memories.",
    tags: ["Team Package", "Full Coverage", "Cinematic"],
    image: "/images/services/cinematic-service.jpg",
  },
];

export const portfolio = [
  {
    id: 1,
    title: "Marathi Bride",
    category: "bridal",
    image: "/images/portfolio/marathi-bride.jpg",
    description: "No filter ahead — pure elegance and charm",
  },
  {
    id: 2,
    title: "Engagement Glamour",
    category: "engagement",
    image: "/images/portfolio/engagement-glamour.jpg",
    description: "Soft glam finish that everyone loved",
  },
  {
    id: 3,
    title: "Natural Beauty Look",
    category: "engagement",
    image: "/images/portfolio/engagement-natural.jpg",
    description: "No lashes, no lenses — just pure natural beauty",
  },
  {
    id: 4,
    title: "Soft Pink Bride",
    category: "bridal",
    image: "/images/portfolio/soft-pink-bride.jpg",
    description: "Soft pink, soft lips — a dreamy bridal look",
  },
  {
    id: 5,
    title: "Engagement Makeover",
    category: "engagement",
    image: "/images/portfolio/engagement-makeover.jpg",
    description: "Make your big day truly special",
  },
  {
    id: 6,
    title: "South Indian Bride",
    category: "south-indian",
    image: "/images/portfolio/south-indian.jpg",
    description: "Traditional South Indian bridal elegance at its best",
  },
  {
    id: 7,
    title: "Reception Glam",
    category: "reception",
    image: "/images/portfolio/reception-glam.jpg",
    description: "Glamorous reception look for the evening celebration",
  },
  {
    id: 8,
    title: "Cinematic Wedding",
    category: "bridal",
    image: "/images/portfolio/cinematic-wedding.jpg",
    description: "Jayesh & Pooja — a cinematic beginning to forever",
  },
  {
    id: 9,
    title: "Flower Art Hair",
    category: "hair",
    image: "/images/portfolio/flower-art.jpg",
    description: "Intricate flower art with full glamour styling",
  },
  {
    id: 10,
    title: "Bengali HD Look",
    category: "bridal",
    image: "/images/portfolio/bengali-hd.jpg",
    description: "Gorgeous Bengali bridal look with HD finish",
  },
  {
    id: 11,
    title: "Wedding Look",
    category: "bridal",
    image: "/images/portfolio/wedding-look.jpg",
    description: "Soft glam, true love, perfect moment",
  },
  {
    id: 12,
    title: "Engagement Soft Glam",
    category: "engagement",
    image: "/images/portfolio/engagement-soft.jpg",
    description: "Beautiful engagement makeover with soft glam finish",
  },
  {
    id: 13,
    title: "Minimal Wedding Look",
    category: "bridal",
    image: "/images/portfolio/minimal-wedding.jpg",
    description: "Less is more — minimal yet stunning bridal look",
  },
  {
    id: 14,
    title: "Glamorous Engagement",
    category: "engagement",
    image: "/images/portfolio/glamorous-engagement.jpg",
    description: "Full glamour engagement — sab dekhte reh gaye!",
  },
  {
    id: 15,
    title: "Engagement Bride",
    category: "engagement",
    image: "/images/portfolio/engagement-bride-1.jpg",
    description: "Elegant engagement bride with perfect finishing",
  },
  {
    id: 16,
    title: "Glamorous Look",
    category: "engagement",
    image: "/images/portfolio/glamorous-engagement-2.jpg",
    description: "Another gorgeous engagement transformation",
  },
  {
    id: 17,
    title: "Reception Makeover",
    category: "reception",
    image: "/images/portfolio/reception-makeover.jpg",
    description: "Reception glamour at its finest",
  },
  {
    id: 18,
    title: "Engagement Beauty",
    category: "engagement",
    image: "/images/portfolio/engagement-bride-2.jpg",
    description: "A beautiful engagement look — natural and graceful",
  },
  {
    id: 19,
    title: "Reception Evening Look",
    category: "reception",
    image: "/images/portfolio/reception-look.jpg",
    description: "Perfect glamorous look for evening receptions",
  },
  {
    id: 20,
    title: "Minimal Bride",
    category: "bridal",
    image: "/images/portfolio/minimal-wedding-2.jpg",
    description: "Less is more — another stunning minimal look",
  },
  {
    id: 21,
    title: "Glowing Wedding Look",
    category: "bridal",
    image: "/images/portfolio/glowing-wedding.jpg",
    description: "A bride glowing with love and happiness",
  },
  {
    id: 22,
    title: "HD Siders Look",
    category: "bridal",
    image: "/images/portfolio/hd-siders-look.jpg",
    description: "Professional siders look with HD finish",
  },
  {
    id: 23,
    title: "Classic Wedding",
    category: "bridal",
    image: "/images/portfolio/wedding-classic.jpg",
    description: "Timeless classic wedding look",
  },
  {
    id: 24,
    title: "Radiant Bride",
    category: "bridal",
    image: "/images/portfolio/glowing-wedding-2.jpg",
    description: "Glow from within — radiant bridal beauty",
  },
  {
    id: 25,
    title: "Reception Queen",
    category: "reception",
    image: "/images/portfolio/reception-makeover-2.jpg",
    description: "The reception queen — all eyes on her",
  },
  {
    id: 26,
    title: "Happy Bride",
    category: "bridal",
    image: "/images/portfolio/glowing-wedding-3.jpg",
    description: "Glowing with happiness — a beautiful bride",
  },
  {
    id: 100,
    title: 'Real Bride Glow',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-001.jpg',
    description: 'Engagement makeover',
  },
  {
    id: 101,
    title: 'Bridal Beauty',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-002.jpg',
    description: 'Engagement makeover',
  },
  {
    id: 102,
    title: 'Wedding Day Magic',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-003.jpg',
    description: 'HD siders look',
  },
  {
    id: 103,
    title: 'Glam Goals',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-004.jpg',
    description: 'Wedding look',
  },
  {
    id: 104,
    title: 'Stunning Look',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-005.jpg',
    description: 'Engagement makeover',
  },
  {
    id: 105,
    title: 'Dreamy Dulhan',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-006.jpg',
    description: 'No filter ahead — pure real beauty',
  },
  {
    id: 106,
    title: 'Picture Perfect',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-007.jpg',
    description: 'HD siders look',
  },
  {
    id: 107,
    title: 'Pure Elegance',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-008.jpg',
    description: 'Wedding look',
  },
  {
    id: 108,
    title: 'Sundar Lagi',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-009.jpg',
    description: 'No filter ahead — pure real beauty',
  },
  {
    id: 109,
    title: 'Wedding Vibes',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-010.jpg',
    description: 'Wedding look',
  },
  {
    id: 110,
    title: 'Bridal Diary',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-011.jpg',
    description: 'Engagement bride',
  },
  {
    id: 111,
    title: 'Soft Glam Story',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-012.jpg',
    description: 'Beautiful glamorous engagement bride',
  },
  {
    id: 112,
    title: 'Gorgeous Bride',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-013.jpg',
    description: 'Minimal wedding look',
  },
  {
    id: 113,
    title: 'Pyaari Dulhan',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-014.jpg',
    description: 'No filter ahead — pure real beauty',
  },
  {
    id: 114,
    title: 'Mehendi Glow',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-015.jpg',
    description: 'Beautiful glamorous engagement bride',
  },
  {
    id: 115,
    title: 'Forever Look',
    category: 'reception',
    image: '/images/portfolio/insta/insta-016.jpg',
    description: 'Reception makeover',
  },
  {
    id: 116,
    title: 'Royal Bride',
    category: 'reception',
    image: '/images/portfolio/insta/insta-017.jpg',
    description: 'Reception makeover',
  },
  {
    id: 117,
    title: 'Modern Glamour',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-018.jpg',
    description: 'Engagement bride',
  },
  {
    id: 118,
    title: 'Timeless Beauty',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-019.jpg',
    description: 'Minimal wedding look',
  },
  {
    id: 119,
    title: 'Wedding Wonder',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-020.jpg',
    description: 'Beautiful glamorous engagement bride',
  },
  {
    id: 120,
    title: 'Bridal Charm',
    category: 'engagement',
    image: '/images/portfolio/insta/insta-021.jpg',
    description: 'Engagement bride',
  },
  {
    id: 121,
    title: 'Real Magic',
    category: 'reception',
    image: '/images/portfolio/insta/insta-022.jpg',
    description: 'Reception makeover',
  },
  {
    id: 122,
    title: 'Sparkle & Shine',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-023.jpg',
    description: 'Glowing with love and happiness',
  },
  {
    id: 123,
    title: 'Pretty in Glam',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-024.jpg',
    description: 'Glowing with love and happiness',
  },
  {
    id: 124,
    title: 'Bride Vibes',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-025.jpg',
    description: 'Glowing with love and happiness',
  },
  {
    id: 125,
    title: 'Cinema Bride',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-026.jpg',
    description: 'Minimal wedding look',
  },
  {
    id: 126,
    title: 'Dream Day Look',
    category: 'bridal',
    image: '/images/portfolio/insta/insta-027.jpg',
    description: 'HD siders look',
  },
];

// Reviews stay in Hinglish — testimonials feel more authentic when raw and personal
export const reviews = [
  {
    name: "Pritam Bhosale",
    text: "Minakshi ne meri shaadi pe kamaal ka kaam kiya! Poore din makeup tikha raha, ek bhi touch-up nahi laga. Exactly wahi look diya jo main chahti thi. Highly recommend her to every bride!",
    rating: 5,
    event: "Bridal Makeup",
    image: "/images/reviews/review-1.jpg",
  },
  {
    name: "Khushboo Chaurasia",
    text: "Best makeup artist in Mumbai! Minakshi has magic in her hands. She gave me a dreamy look for my engagement. The no-lash look was exactly what I wanted — natural yet glamorous. Bohot shukriya!",
    rating: 5,
    event: "Engagement Makeup",
    image: "/images/reviews/review-2.jpg",
  },
  {
    name: "Rupa Borkar",
    text: "I was so nervous about my wedding makeup but Minakshi made me completely relax. She did a trial session first and on the wedding day my look was absolutely perfect. Meri family roo padi mujhe dekh ke — best compliment ever!",
    rating: 5,
    event: "Bridal Makeup",
    image: "/images/reviews/review-3.jpg",
  },
  {
    name: "Dr. Surve",
    text: "Minakshi did my engagement look without lashes and without lenses — just pure natural beauty. Everyone thought I had professional editing done but it was all her skill! Worth every penny.",
    rating: 5,
    event: "Engagement Makeup",
    image: "/images/reviews/review-4.jpg",
  },
  {
    name: "Pooja Hule",
    text: "Minakshi handled my complete wedding look along with the Shutter Snap Photography team. The coordination was flawless — makeup, hair, photos, video — everything came together beautifully. Dream team hai ye!",
    rating: 5,
    event: "Wedding Package",
    image: "/images/reviews/review-5.jpg",
  },
];

export const vendorPartners = [
  {
    name: "Shutter Snap Photography",
    role: "Wedding Photography",
    instagram: "@shutter_snap_photography_20",
  },
  {
    name: "Shutter Soul Studio",
    role: "Cinematography",
    instagram: "@shuttersoul__studio",
  },
  {
    name: "Vid Tam Photography",
    role: "Video Editing",
    instagram: "@vid.tam_pho2graphy",
  },
];

export const processSteps = [
  {
    step: 1,
    title: "Inquiry",
    description: "Reach out via WhatsApp or our contact form. Tell us about your event, date, and the look you envision.",
    icon: "message",
  },
  {
    step: 2,
    title: "Consultation",
    description: "We discuss your outfit, jewellery, venue, and preferences in detail. Together we create your perfect look concept.",
    icon: "sparkle",
  },
  {
    step: 3,
    title: "Trial Session",
    description: "A pre-wedding trial to finalize your look. We fine-tune every detail until you are absolutely in love with it.",
    icon: "palette",
  },
  {
    step: 4,
    title: "Aapka Big Day",
    description: "On the day, we arrive early, set up, and create magic. You relax — we'll make you look your most beautiful self.",
    icon: "crown",
  },
];

export const marqueeItems = [
  "Bridal Makeup",
  "Engagement Looks",
  "Hair Styling",
  "South Indian Bridal",
  "Bengali Bridal",
  "Buddhist Wedding",
  "Reception Glam",
  "Baby Shower",
  "Groom Makeover",
  "HD Makeup",
  "Soft Glam",
  "Destination Wedding",
];

export const portfolioCategories = [
  { id: "all", label: "All" },
  { id: "bridal", label: "Bridal" },
  { id: "engagement", label: "Engagement" },
  { id: "south-indian", label: "South Indian" },
  { id: "reception", label: "Reception" },
  { id: "hair", label: "Hair Styling" },
];
